"""Pydantic response models for all API endpoints.

These enable:
  1. Proper OpenAPI/Swagger documentation (auto-generated by FastAPI)
  2. Response validation (catches bugs before they reach the client)
  3. Future SDK codegen (e.g. openapi-generator, fern)
"""
from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from typing import Optional, List, Dict, Any


# ── Common ───────────────────────────────────────────────────────────────────

class OkResponse(BaseModel):
    ok: bool = True

class OkRestartResponse(BaseModel):
    ok: bool = True
    restart_required: bool = False


# ── Workflow ─────────────────────────────────────────────────────────────────

class WorkflowResponse(BaseModel):
    id: str
    name: str
    description: str = ""
    tags: List[str] = []
    created_at: str
    run_count: int = 0

    model_config = ConfigDict(extra="allow")


# ── Eval Run ─────────────────────────────────────────────────────────────────

class EvalRunStatsResponse(BaseModel):
    total: int = 0
    decided: int = 0
    pending: int = 0
    avg_divergence: Optional[float] = None
    divergence_buckets: List[int] = []
    comparisons: List[Dict[str, Any]] = []
    choice_breakdown: Optional[Dict[str, int]] = None
    tokens_a: int = 0
    tokens_a_out: int = 0
    tokens_b: int = 0
    tokens_b_out: int = 0

    model_config = ConfigDict(extra="allow")

class EvalRunResponse(BaseModel):
    id: str
    workflow_id: str
    name: str
    description: str = ""
    status: str
    branch_a_config: Dict[str, Any] = {}
    branch_b_config: Dict[str, Any] = {}
    test_set_id: Optional[str] = None
    total_cases: int = 0
    created_at: str
    stats: Optional[EvalRunStatsResponse] = None

    model_config = ConfigDict(extra="allow")


# ── Test Set ─────────────────────────────────────────────────────────────────

class TestCaseResponse(BaseModel):
    id: str
    test_set_id: str
    label: str
    input_data: Dict[str, Any] = {}
    tags: List[str] = []
    expected_output: Optional[str] = None
    created_at: str

    model_config = ConfigDict(extra="allow")

class TestSetResponse(BaseModel):
    id: str
    name: str
    description: str = ""
    workflow_id: Optional[str] = None
    created_at: str
    case_count: int = 0
    version: int = 1
    is_frozen: bool = False

    model_config = ConfigDict(extra="allow")

class TestSetDetailResponse(TestSetResponse):
    cases: List[TestCaseResponse] = []


# ── Comparison ───────────────────────────────────────────────────────────────

class ComparisonResponse(BaseModel):
    id: str
    run_id: str
    workflow_id: Optional[str] = None
    branch_a_id: str
    branch_b_id: str
    divergence_score: Optional[float] = None
    scoring_status: str = "pending"
    decided: bool = False
    decision_id: Optional[str] = None
    eval_run_id: Optional[str] = None
    test_case_label: str = ""
    created_at: str

    model_config = ConfigDict(extra="allow")

class ScoreStatusResponse(BaseModel):
    id: str
    scoring_status: str
    divergence_score: Optional[float] = None
    step_divergence_scores: Dict[str, float] = {}
    eval_results: List[Dict[str, Any]] = []


# ── Decision ─────────────────────────────────────────────────────────────────

class DecisionResponse(BaseModel):
    id: str
    comparison_id: str
    run_id: str
    workflow_id: Optional[str] = None
    reviewer_id: str
    choice: str
    confidence: str
    rationale_for_choice: str
    rationale_for_rejection: str = ""
    tags: List[str] = []
    divergence_score: Optional[float] = None
    created_at: str

    model_config = ConfigDict(extra="allow")


# ── API Key ──────────────────────────────────────────────────────────────────

class ApiKeyResponse(BaseModel):
    id: str
    name: str
    prefix: str
    created_at: str
    is_active: bool = True

    model_config = ConfigDict(extra="allow")

class ApiKeyCreateResponse(ApiKeyResponse):
    raw_key: str


# ── Branch / Step ────────────────────────────────────────────────────────────

class BranchResponse(BaseModel):
    id: str
    run_id: str
    workflow_id: Optional[str] = None
    name: str
    model_id: str
    temperature: float = 0.7
    created_at: str

    model_config = ConfigDict(extra="allow")

class StepOutputResponse(BaseModel):
    id: str
    run_id: str
    branch_id: str
    step_name: str
    step_index: int
    output_text: str
    model_id: str
    tokens_input: int = 0
    tokens_output: int = 0
    latency_ms: int = 0
    created_at: str

    model_config = ConfigDict(extra="allow")


# ── Run ──────────────────────────────────────────────────────────────────────

class RunResponse(BaseModel):
    id: str
    workflow_id: str
    status: str
    input_data: Dict[str, Any] = {}
    metadata: Dict[str, Any] = {}
    created_at: str
    completed_at: Optional[str] = None

    model_config = ConfigDict(extra="allow")

class RunDetailResponse(RunResponse):
    branches: List[BranchResponse] = []
    steps: List[StepOutputResponse] = []
    comparisons: List[ComparisonResponse] = []


# ── Stats ────────────────────────────────────────────────────────────────────

class StatsResponse(BaseModel):
    workflows: int = 0
    eval_runs: int = 0
    comparisons: int = 0
    decisions: int = 0
    divergence_scorer: str = "auto"

    model_config = ConfigDict(extra="allow")

class ChartBucket(BaseModel):
    range: str
    count: int

class CostPoint(BaseModel):
    date: str
    cost: float
    tokens: int
    steps: int

class ChartsResponse(BaseModel):
    divergence_histogram: List[ChartBucket] = []
    cost_over_time: List[CostPoint] = []


# ── Settings ─────────────────────────────────────────────────────────────────

class SettingsResponse(BaseModel):
    openai_api_key_set: bool = False
    openai_api_key_masked: Optional[str] = None
    divergence_scorer: str = "auto"
    st_model: str = ""
    embed_model: str = ""
    theme: str = "dark"
    display_name: str = ""
    timezone: str = ""

    model_config = ConfigDict(extra="allow")

class SystemInfoResponse(BaseModel):
    storage: str = "sqlite"
    database_url_set: bool = False
    version: str
    background_workers: int = 4
    require_ui_auth: bool = False
    multi_tenant: bool = False
    otel_enabled: bool = False

    model_config = ConfigDict(extra="allow")


# ── Health ───────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str
    version: Optional[str] = None

class ReadinessResponse(BaseModel):
    status: str
    checks: Dict[str, str] = {}


# ── Provider ─────────────────────────────────────────────────────────────

class ProviderResponse(BaseModel):
    id: str
    name: str
    provider_type: str = "openai"
    base_url: str = ""
    api_key_set: bool = False
    api_key_masked: str = ""
    is_default: bool = False
    created_at: str
    updated_at: str

    model_config = ConfigDict(extra="allow")

class ProviderTestResponse(BaseModel):
    ok: bool
    message: str
    latency_ms: int = 0


# ── Runner ───────────────────────────────────────────────────────────────────

class RunnerResponse(BaseModel):
    eval_run_id: str
    errors: List[str] = []

class PlaygroundResponse(BaseModel):
    comparison_id: str
    run_id: str
    model_a: Dict[str, Any]
    model_b: Dict[str, Any]
    divergence_score: Optional[float] = None
    divergence_summary: str = ""


# ── Demo ─────────────────────────────────────────────────────────────────────

class DemoInfo(BaseModel):
    name: str
    display_name: str
    workflow_name: str
    eval_run_name: str
    description: str = ""
    cases: int
    steps: int
    step_names: List[str] = []

class SeedResult(BaseModel):
    seeded: int
    errors: int
    results: List[Dict[str, Any]]

class PruneResponse(BaseModel):
    deleted_rows: int
    older_than_days: int
